name = "backend"
compatibility_date = "2024-09-06"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTYwMzg5M2MtNzU2MS00MDkzLTkwOTktNDJkNGQ5NGVmZTRiIiwidGVuYW50X2lkIjoiMjViODZhNGJkZTczM2E3OTk4M2Q1ZTNhODc1ZTBhNzQ0OGYxNTdiM2Y5MDBiYjEwY2Q3Njk1NjJkMjJiZjZmYSIsImludGVybmFsX3NlY3JldCI6ImUzZGVlNDc0LTFlMWMtNDYwNy1iZDg4LWJhZDgxYjZmYTNkYSJ9.GgGjuaqgHk4fe7rQdxwSU6dSGgD3iCsEbR0Wg2amAMc"

JWT_SECRET="karthikcapone"

